site_name: Siddhi-IO-Report
site_description: Siddhi IO Report Extension
site_author: WSO2
site_url: https://kts-desilva.github.io/siddhi-io-report-original/
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
repo_name: Siddhi-IO-Email
repo_url: https://github.com/kts-desilva/siddhi-io-report-original
copyright: Copyright &copy; 2011 - 2018 WSO2
theme:
  name: material
  logo: images/siddhi-logo-w.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
extra:
  social:
  - type: github
    link: https://github.com/wso2/siddhi
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
markdown_extensions:
- admonition
- toc(permalink=true)
- codehilite(guess_lang=false)
pages:
- Welcome: index.md
- API Docs:
  - latest: api/latest.md
- License: license.md